project:
  type: website
  output-dir: docs
  resources:
     - "css"

website:
  title: "Thomas Lamy"
  description: "The personal website of Thomas Lamy"
  site-url: https://thomaslamy.com
  image: images/tlamy_circle2.png
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: false
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "News"
        href: news/index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "People"
        href: people.qmd
  page-footer:
    left: "© 2026 Thomas Lamy · IRD, UMR MARBEC"
    center: "[Image credits](/credits.qmd)"
    right:
      - icon: envelope
        href: "mailto:thomas.lamy@ird.fr"
        aria-label: Email
      - text: "ORCID"
        href: "https://orcid.org/0000-0002-7881-0578"   

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_includes/header.html"
